workflows:
  default:
    name: Build Android APK
    max_build_duration: 60  # Optional: maximum time for the build to run (in minutes)
    
    environment:
      flutter: stable  # Only if you're using Flutter, otherwise skip it
      node: 16  # Specify the version of Node.js you're using
      
    scripts:
      # Install dependencies (npm install for React Native)
      - name: Install dependencies
        script: |
          npm install

      # Build APK using Gradle
      - name: Build APK
        script: |
          cd android && ./gradlew assembleRelease

    artifacts:
      # Location of the APK that will be generated
      - android/app/build/outputs/apk/release/app-release.apk

    publishing:
      # Publishing is now handled by `email` in a valid structure
      email:
      recipients:
        - 'johnciapalmer@gmail.com'
